node {

  try {
      stage('Preparation') {
         checkout scm
      }

      stage('Build') {
         
         withCredentials([
	    string(credentialsId: 'jenkins-aws-secret-key-id', variable: 'AWS_ACCESS_KEY_ID'),
            string(credentialsId: 'jenkins-aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY'),
            sshUserPrivateKey(credentialsId: "ubuntu-ec2", keyFileVariable: 'UBUNTU_EC2')
         ]) {
            sh "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
            sh "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
            if (params.ACTION == "create") { 
              sh "cat $UBUNTU_EC2 > ./tutorial.pem && chmod 0600 ./tutorial.pem"
              sh "cp ec2/main.tf ."
              sh "./terraform init -reconfigure"
              sh "./terraform plan"
              sh "./terraform apply -auto-approve"
              sh "rm ./tutorial.pem"
            } else if (params.ACTION == "destroy") {
              sh "./terraform destroy -auto-approve"
            } else {
              print "Nothing to do"
            }
         }

      }

    } catch(e) {
       throw e;
   }                                     
}       
