node {

  try {
      stage('Preparation') {
         checkout scm
      }

      stage('Build') {
         
         withCredentials([
	    string(credentialsId: 'jenkins-aws-secret-key-id', variable: 'AWS_ACCESS_KEY_ID'),
            string(credentialsId: 'jenkins-aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY'),
            sshUserPrivateKey(credentialsId: "ubuntu-ec2", keyFileVariable: 'UBUNTU_EC2')
         ]) {
            sh "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
            sh "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
            sh "cat $UBUNTU_EC2 > ./tutorial.pem && chmod 0600 ./tutorial.pem"
            sh "cp ec2/main.tf ."
            sh "if [[ ! -e $JENKINS_HOME/terraform ]]; then"
            sh "   mkdir -p $JENKINS_HOME/terraform && cp terraform $JENKINS_HOME/terraform/; "
            sh "fi"
            sh "$JENKINS_HOME/terraform/terraform init"
            sh "$JENKINS_HOME/terraform/terraform plan"
            sh "$JENKINS_HOME/terraform/terraform apply -auto-approve"
            sh "rm ./tutorial.pem"
         }

      }

    } catch(e) {
       throw e;
   }                                     
}       
