node {

  try {
      stage('Preparation') {
         checkout scm
      }

      stage('Build') {
         
         withCredentials([
	    string(credentialsId: 'jenkins-aws-secret-key-id', variable: 'AWS_ACCESS_KEY_ID'),
            string(credentialsId: 'jenkins-aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY'),
            sshUserPrivateKey(credentialsId: "ubuntu-ec2", keyFileVariable: 'UBUNTU_EC2')
         ]) {
            sh "cd ../../"
            sh "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
            sh "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
            sh "echo $UBUNTU_EC2 > ./tutorial.pem "
            sh "pwd && ls -la"
            sh "./terraform init"
            sh "./terraform plan"
            sh "./terraform apply -auto-approve"
         }

      }

    } catch(e) {
       throw e;
   }                                     
}       
