node {

  try {
      stage('Preparation') {
         checkout scm
      }

      stage('Build') {
         
         withCredentials([
	    string(credentialsId: 'jenkins-aws-secret-key-id', variable: 'AWS_ACCESS_KEY_ID'),
            string(credentialsId: 'jenkins-aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY'),
         ]) {
            sh "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
            sh "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
            if (params.ACTION == "create") {
              sh "cp s3/main.tf ."
              sh "./terraform init -force-copy"
              sh "./terraform plan"
              sh "./terraform apply -auto-approve"
            } else if (params.ACTION == "destroy") {
              sh "./terraform destroy -auto-approve"
            } else {
              print "Nothing to do"
            }
         }

      }

    } catch(e) {
       throw e;
   }                                     
}       
