node {

  try {
      stage('Preparation') {
         checkout scm
      }

      stage('Build') {
         sh "pwd && ansible --version && cd ../../ansible && ls -la"
         ansiblePlaybook inventory: '../../ansible/hosts', playbook: '../../ansible/provisioner.yml' 
      }

    } catch(e) {
       throw e;
   }                                     
}       
